### ISSUE TITLE
servd-asset-storage/local/pull-assets synchronises assets, then deletes everything, in dev

### ISSUE THREAD

**Issue by howells** [servdhost/craft-asset-storage#25]
With "Use Local Volumes During Dev" set to true, it seems new assets are downloaded initially, but then the script proceeds to delete everything locally.

To get it to work, I have to delete the entire servd-volumes folder, and then run the script again, which successfully pulls all the files. I'd prefer if the script didn't even attempt to delete orphaned files.

![CleanShot 2021-08-26 at 11 26 40@2x](https://user-images.githubusercontent.com/145849/130947182-632764db-e0df-42d9-bffa-812d94a4219e.png)

**Comment by mattgrayisok** [comment]
Hey @howells I've haven't been able to recreate this issue but I think it must be being caused by some filesystem path string not matching when the plugin expects them to (double slashes or symlinks or something). Does anything like that spring to mind as a possibility?

Either way, I've just released 2.4.3 which contains a `--skipDelete` flag which you can use when pulling or pushing files from your local filesystem. When that is set the plugin simply won't delete anything.

**Comment by howells** [comment]
@mattgrayisok seems to work well, thanks!
