### ISSUE TITLE
Support for multiple "local" environments?

### ISSUE THREAD

**Issue by johndwells** [servdhost/craft-asset-storage#4]
We have a project being worked on by multiple devs; is it possible for each of us to have our own "local" asset storage folder? Under the hood does the path simply use `CRAFT_ENVIRONMENT`?

Alternatively are there ways to use an actual local volume for certain environments?

**Comment by mattgrayisok** [comment]
There's not currently any way to switch between local and Servd's Asset Platform whilst using the same asset as defined in a project config, but I'll think about if I can add that potentially as an ENV var override which you can set for local dev.

RE multiple local environments, my preferred method is to set the volume's path prefix to an env var and then get each developer to set a different value and leave it blank in staging and prod. This should work for the time being.

I'm planning on adding the ability to clone assets from the local environment to staging and prod (and vice-versa) which could potentially make this arrangement less appealing if you want to use that functionality in the future.

I'll have a think about alternatives and drop a note here if anything springs to mind.

**Comment by johndwells** [comment]
> There's not currently any way to switch between local and Servd's Asset Platform whilst using the same volume as defined in a project config, but I'll think about if I can add that potentially as an ENV var override which you can set for local dev.

Maybe there's a way to override it within `config/app.php`. I have no idea, but know that for example I use `config/app.php` override the mail adapter programmatically for local environments.

> RE multiple local environments, my preferred method is to set the volume's path prefix to an env var and then get each developer to set a different value and leave it blank in staging and prod. This should work for the time being.

Seems that would work just fine.

> I'm planning on adding the ability to clone assets from the local environment to staging and prod (and vice-versa) which could potentially make this arrangement less appealing if you want to use that functionality in the future.

I think syncing prod/staging _to local_ would be a neat achievement.

I'm still figuring out the best workflow when working on this sort of architecture. In my typical setup, I use [craft-scripts ](https://github.com/nystudio107/craft-scripts) to pull down db and assets whenever I need to get my local environment synced up with prod/staging. It works well, and works well for multiple devs, each able to control their own local setups.

**Comment by mattgrayisok** [comment]
My ultimate aim is to get all of this baked into the plugin, so you could trigger pull syncs from inside the Craft dashboard.

This is relatively easy for staging and production as it'd just be a different way to trigger the existing Servd clone capability. For local dev I'm thinking it could:

- Trigger an assets clone from 'source env' to 'local' (as 'local' assets are actually in Servd's asset platform this is straight forward)
- Fork a background PHP process which downloads a db dump from 'source env' and imports into the local db by just hijacking Craft's existing config files.

This way you get one-click local syncing from any active Servd environment all delivered via the Craft dashboard.

(I also have an idea for how to make this work cloning from local to staging and production, but that's a bit crazy so I'll save it for another day)

Multi-developer setups are only difficult because Servd has a single asset store for each environment - as you've discovered. The subfolder solution above works ok, but makes the local store structurally different from all other environments, so cloning between them becomes an issue.

One option is to have local as a special case which can contain multiple 'sub' environments:

```
local/default
local/dev1
local/dev2
```

If Servd were to be made aware of this it could default to `default` for cloning operations, but allow that to be overridden in the specific case of local operations.

Any thoughts or opinions are much appreciated.

**Comment by mattgrayisok** [comment]
Releasae 1.3.9 allows you to use an env var to set the environment to an env var to replace to auto-detected env. I'd recommend setting this to an env var and using values  like `local/developer-name` during local dev which will allow all developers to have their own independent assets storage.

I'll also be adding the option to use local storage during local development, even when an asset volume is set up to use the Servd Assets Platform, which will also solve the problem in a way which doesn't count towards your total assets storage on Servd.

This might need to change again in the future in order to support cloning from local as mentioned above, but as that's likely a little way off, I think solving this use-case as simply as possible is more important in the short term.

**Comment by johndwells** [comment]
@mattgrayisok This is a great solution even if short term, thanks!

FWIW I did notice this KB article mentioned in the latest Craft Link List issue, about using local volumes for development:

https://craftcms.com/knowledge-base/using-local-volumes-for-development
