### ISSUE TITLE
Blitz integration with Servd's Static Cache

### ISSUE THREAD

**Issue by mattgrayisok** [servdhost/craft-asset-storage#53]
Create a custom cache purger for blitz which allows it to interact with Servd's Static cache.

The cache would need to be configured to respect origin cache headers which would be set by Blitz based on its plugin settings.

Cache clearing would be handled by Blitz + the custom purge controller.

We'd need a way to disable all other Servd Static Cache integrations which are otherwise provided by this plugin to prevent the two from interacting.

https://putyourlightson.com/plugins/blitz#reverse-proxy-purgers

**Comment by mattgrayisok** [comment]
Working on this in #54

**Comment by mattgrayisok** [comment]
Released in 2.7.0 and 3.1.1

**Comment by engram-design** [comment]
Thanks for taking to time to look at this, looking forward to diving into it!

**Comment by shoored** [comment]
Hey! I've had Blitz on this particular site before switching to Servd for hosting. So now I have configured both Blitz and the Servd plugin as the docs suggest. 

Since Static Cashing has to be enabled in the Servd environment, we now get both the Blitz cache panel and the Servd cache panel in Entry detail sidebars. 

<img width="380" alt="image" src="https://github.com/user-attachments/assets/6a234745-3f31-45c3-bb74-ee5f91bf426b">


I can probably hide the Servd panel for clients with plugin permissions, but it seems the button "Purge Entry URL(s)" does not do anything anymore? 

I was wondering if it's possible to check if Blitz is used for caching and have the Servd panel say "Caching is done by Blitz" or something, perhaps even removing that panel alltogether?

Not sure if this is correct behaviour or I missed a step somewhere.
