### ISSUE TITLE
Use remote asset source for local dev

### ISSUE THREAD

**Issue by jsunsawyer** [servdhost/craft-asset-storage#8]
I can switch the environment from `dev` to `staging` to get remote assets for local dev, but switching this can mess up some other settings (multi-environment general config, SEOmatic, etc.).

Would be nice if there was an environment setting to adjust this.

**Comment by mattgrayisok** [comment]
I'm currently working on a quick fix for this which will allow you to overwrite the automatically detected environment to use any string you prefer. 

I'll also be reviewing the entire local dev process asap to make this all feel a bit nicer and hopefully make more sense as a unified development flow rather than a load of options which just fill in the gaps

**Comment by mattgrayisok** [comment]
Just released this in 1.3.9. The new setting in in the plugin settings page.

The setting will be added to project config so I'd recommend adding it as an env var. If the env var is not set in a particular environment or it is blank, the plugin will fall back to using the auto detected value.

**Comment by jsunsawyer** [comment]
@mattgrayisok Thanks, this works great and will help a ton.

One thing though, the default `$SERVD_ASSETS_ENVIRONMENT` isn't being used, so you have to manually populate that env var to get it to work. This is inconsistent with how the defaults work when setting up asset volumes.

**Comment by jsunsawyer** [comment]
@mattgrayisok Just tried to use `production` assets in our staging environment by setting an env variable in Servd and it's still trying to pull assets from the staging directory. Is it not currently possible to override the assets environment on staging?
